ALTER TABLE schema
    ADD name VARCHAR(255);

ALTER TABLE measurement
    ADD CONSTRAINT FK_MEASUREMENT_ON_CAR FOREIGN KEY (car_id) REFERENCES car (id);

ALTER TABLE measurement
    ADD CONSTRAINT FK_MEASUREMENT_ON_SCHEMA FOREIGN KEY (schema_id) REFERENCES schema (id);

ALTER TABLE schema_car
    ADD CONSTRAINT FK_SCHEMACAR_ON_CAR FOREIGN KEY (car_id) REFERENCES car (id);

ALTER TABLE schema_car
    ADD CONSTRAINT FK_SCHEMACAR_ON_SCHEMA FOREIGN KEY (schema_id) REFERENCES schema (id);

ALTER TABLE measurement
    ALTER COLUMN car_id DROP NOT NULL;