CREATE TABLE "user"
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255),
    password_hash VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE car
    ADD last_live TIMESTAMP WITHOUT TIME ZONE;