CREATE TABLE alert
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    key_name        VARCHAR(255),
    min_value       DOUBLE PRECISION,
    max_value       DOUBLE PRECISION,
    forbidden_value VARCHAR(255),
    exists_boolean  BOOLEAN,
    car_id          INTEGER,
    CONSTRAINT pk_alert PRIMARY KEY (id)
);

CREATE TABLE alert_history
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    measurement_id INTEGER,
    alert_id       INTEGER,
    CONSTRAINT pk_alerthistory PRIMARY KEY (id)
);

CREATE TABLE car
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    license_plate VARCHAR(255),
    vin           VARCHAR(255),
    last_live     TIMESTAMP WITHOUT TIME ZONE,
    fleet_id      INTEGER,
    CONSTRAINT pk_car PRIMARY KEY (id)
);

CREATE TABLE field
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_list   BOOLEAN                                  NOT NULL,
    filed_key VARCHAR(255),
    type      VARCHAR(255),
    schema_id INTEGER,
    CONSTRAINT pk_field PRIMARY KEY (id)
);

CREATE TABLE fleet
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_fleet PRIMARY KEY (id)
);

CREATE TABLE measurement
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    data      VARCHAR(255),
    schema_id INTEGER,
    car_id    INTEGER,
    CONSTRAINT pk_measurement PRIMARY KEY (id)
);

CREATE TABLE schema
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_schema PRIMARY KEY (id)
);

CREATE TABLE schema_car
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schema_id INTEGER,
    car_id    INTEGER,
    CONSTRAINT pk_schemacar PRIMARY KEY (id)
);

CREATE TABLE public."user"
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255),
    password_hash VARCHAR(255),
    role          VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE alert_history
    ADD CONSTRAINT FK_ALERTHISTORY_ON_ALERT FOREIGN KEY (alert_id) REFERENCES alert (id);

ALTER TABLE alert_history
    ADD CONSTRAINT FK_ALERTHISTORY_ON_MEASUREMENT FOREIGN KEY (measurement_id) REFERENCES measurement (id);

ALTER TABLE alert
    ADD CONSTRAINT FK_ALERT_ON_CAR FOREIGN KEY (car_id) REFERENCES car (id);

ALTER TABLE car
    ADD CONSTRAINT FK_CAR_ON_FLEET FOREIGN KEY (fleet_id) REFERENCES fleet (id);

ALTER TABLE field
    ADD CONSTRAINT FK_FIELD_ON_SCHEMA FOREIGN KEY (schema_id) REFERENCES schema (id);

ALTER TABLE measurement
    ADD CONSTRAINT FK_MEASUREMENT_ON_CAR FOREIGN KEY (car_id) REFERENCES car (id);

ALTER TABLE measurement
    ADD CONSTRAINT FK_MEASUREMENT_ON_SCHEMA FOREIGN KEY (schema_id) REFERENCES schema (id);

ALTER TABLE schema_car
    ADD CONSTRAINT FK_SCHEMACAR_ON_CAR FOREIGN KEY (car_id) REFERENCES car (id);

ALTER TABLE schema_car
    ADD CONSTRAINT FK_SCHEMACAR_ON_SCHEMA FOREIGN KEY (schema_id) REFERENCES schema (id);

INSERT INTO "public".user(id, email, password_hash, role)
VALUES (1, 'admin@fleetbrother.com', '$2a$12$aJG1ZpdsoWk1Sr6lYUUB5OP8WKIYVLzeMTPywn46iDVU.YRpQqTYy', 'ADMIN');